include("../AWSCorePrototypeServices.jl")
using .Services: accessanalyzer

"""
Retrieves a list of tags applied to the specified resource.
"""
ListTagsForResource(resourceArn) = accessanalyzer("GET", "/tags/$resourceArn")
ListTagsForResource(resourceArn, args) = accessanalyzer("GET", "/tags/$resourceArn", args)
ListTagsForResource(a...; b...) = ListTagsForResource(a..., b)

"""
Retrieves information about a resource that was analyzed.
"""
GetAnalyzedResource(analyzerArn, resourceArn) = accessanalyzer("GET", "/analyzed-resource")
GetAnalyzedResource(analyzerArn, resourceArn, args) = accessanalyzer("GET", "/analyzed-resource", args)
GetAnalyzedResource(a...; b...) = GetAnalyzedResource(a..., b)

"""
Creates an analyzer for your account.
"""
CreateAnalyzer(analyzerName, type) = accessanalyzer("PUT", "/analyzer")
CreateAnalyzer(analyzerName, type, args) = accessanalyzer("PUT", "/analyzer", args)
CreateAnalyzer(a...; b...) = CreateAnalyzer(a..., b)

"""
Retrieves a list of findings generated by the specified analyzer.
"""
ListFindings(analyzerArn) = accessanalyzer("POST", "/finding")
ListFindings(analyzerArn, args) = accessanalyzer("POST", "/finding", args)
ListFindings(a...; b...) = ListFindings(a..., b)

"""
Retrieves information about the specified finding.
"""
GetFinding(analyzerArn, id) = accessanalyzer("GET", "/finding/$id")
GetFinding(analyzerArn, id, args) = accessanalyzer("GET", "/finding/$id", args)
GetFinding(a...; b...) = GetFinding(a..., b)

"""
Retrieves a list of archive rules created for the specified analyzer.
"""
ListArchiveRules(analyzerName) = accessanalyzer("GET", "/analyzer/$analyzerName/archive-rule")
ListArchiveRules(analyzerName, args) = accessanalyzer("GET", "/analyzer/$analyzerName/archive-rule", args)
ListArchiveRules(a...; b...) = ListArchiveRules(a..., b)

"""
Immediately starts a scan of the policies applied to the specified resource.
"""
StartResourceScan(analyzerArn, resourceArn) = accessanalyzer("POST", "/resource/scan")
StartResourceScan(analyzerArn, resourceArn, args) = accessanalyzer("POST", "/resource/scan", args)
StartResourceScan(a...; b...) = StartResourceScan(a..., b)

"""
Retrieves a list of analyzers.
"""
ListAnalyzers() = accessanalyzer("GET", "/analyzer")
ListAnalyzers(, args) = accessanalyzer("GET", "/analyzer", args)
ListAnalyzers(a...; b...) = ListAnalyzers(a..., b)

"""
Retrieves information about the specified analyzer.
"""
GetAnalyzer(analyzerName) = accessanalyzer("GET", "/analyzer/$analyzerName")
GetAnalyzer(analyzerName, args) = accessanalyzer("GET", "/analyzer/$analyzerName", args)
GetAnalyzer(a...; b...) = GetAnalyzer(a..., b)

"""
Adds a tag to the specified resource.
"""
TagResource(resourceArn, tags) = accessanalyzer("POST", "/tags/$resourceArn")
TagResource(resourceArn, tags, args) = accessanalyzer("POST", "/tags/$resourceArn", args)
TagResource(a...; b...) = TagResource(a..., b)

"""
Removes a tag from the specified resource.
"""
UntagResource(resourceArn, tagKeys) = accessanalyzer("DELETE", "/tags/$resourceArn")
UntagResource(resourceArn, tagKeys, args) = accessanalyzer("DELETE", "/tags/$resourceArn", args)
UntagResource(a...; b...) = UntagResource(a..., b)

"""
Creates an archive rule for the specified analyzer. Archive rules automatically archive findings that meet the criteria you define when you create the rule.
"""
CreateArchiveRule(analyzerName, filter, ruleName) = accessanalyzer("PUT", "/analyzer/$analyzerName/archive-rule")
CreateArchiveRule(analyzerName, filter, ruleName, args) = accessanalyzer("PUT", "/analyzer/$analyzerName/archive-rule", args)
CreateArchiveRule(a...; b...) = CreateArchiveRule(a..., b)

"""
Retrieves information about an archive rule.
"""
GetArchiveRule(analyzerName, ruleName) = accessanalyzer("GET", "/analyzer/$analyzerName/archive-rule/$ruleName")
GetArchiveRule(analyzerName, ruleName, args) = accessanalyzer("GET", "/analyzer/$analyzerName/archive-rule/$ruleName", args)
GetArchiveRule(a...; b...) = GetArchiveRule(a..., b)

"""
Deletes the specified archive rule.
"""
DeleteArchiveRule(analyzerName, ruleName) = accessanalyzer("DELETE", "/analyzer/$analyzerName/archive-rule/$ruleName")
DeleteArchiveRule(analyzerName, ruleName, args) = accessanalyzer("DELETE", "/analyzer/$analyzerName/archive-rule/$ruleName", args)
DeleteArchiveRule(a...; b...) = DeleteArchiveRule(a..., b)

"""
Deletes the specified analyzer. When you delete an analyzer, Access Analyzer is disabled for the account in the current or specific Region. All findings that were generated by the analyzer are deleted. You cannot undo this action.
"""
DeleteAnalyzer(analyzerName) = accessanalyzer("DELETE", "/analyzer/$analyzerName")
DeleteAnalyzer(analyzerName, args) = accessanalyzer("DELETE", "/analyzer/$analyzerName", args)
DeleteAnalyzer(a...; b...) = DeleteAnalyzer(a..., b)

"""
Retrieves a list of resources of the specified type that have been analyzed by the specified analyzer..
"""
ListAnalyzedResources(analyzerArn) = accessanalyzer("POST", "/analyzed-resource")
ListAnalyzedResources(analyzerArn, args) = accessanalyzer("POST", "/analyzed-resource", args)
ListAnalyzedResources(a...; b...) = ListAnalyzedResources(a..., b)

"""
Updates the criteria and values for the specified archive rule.
"""
UpdateArchiveRule(analyzerName, filter, ruleName) = accessanalyzer("PUT", "/analyzer/$analyzerName/archive-rule/$ruleName")
UpdateArchiveRule(analyzerName, filter, ruleName, args) = accessanalyzer("PUT", "/analyzer/$analyzerName/archive-rule/$ruleName", args)
UpdateArchiveRule(a...; b...) = UpdateArchiveRule(a..., b)

"""
Updates the status for the specified findings.
"""
UpdateFindings(analyzerArn, status) = accessanalyzer("PUT", "/finding")
UpdateFindings(analyzerArn, status, args) = accessanalyzer("PUT", "/finding", args)
UpdateFindings(a...; b...) = UpdateFindings(a..., b)
