include("../AWSCorePrototypeServices.jl")
using .Services: accessanalyzer

"""
Retrieves a list of tags applied to the specified resource.

Required Parameters:
resourceArn
"""
ListTagsForResource(args) = accessanalyzer("GET", "/tags/{resourceArn}", args)

"""
Retrieves information about a resource that was analyzed.

Required Parameters:
analyzerArn, resourceArn
"""
GetAnalyzedResource(args) = accessanalyzer("GET", "/analyzed-resource", args)

"""
Creates an analyzer for your account.

Required Parameters:
analyzerName, type
"""
CreateAnalyzer(args) = accessanalyzer("PUT", "/analyzer", args)

"""
Retrieves a list of findings generated by the specified analyzer.

Required Parameters:
analyzerArn
"""
ListFindings(args) = accessanalyzer("POST", "/finding", args)

"""
Retrieves information about the specified finding.

Required Parameters:
analyzerArn, id
"""
GetFinding(args) = accessanalyzer("GET", "/finding/{id}", args)

"""
Retrieves a list of archive rules created for the specified analyzer.

Required Parameters:
analyzerName
"""
ListArchiveRules(args) = accessanalyzer("GET", "/analyzer/{analyzerName}/archive-rule", args)

"""
Immediately starts a scan of the policies applied to the specified resource.

Required Parameters:
analyzerArn, resourceArn
"""
StartResourceScan(args) = accessanalyzer("POST", "/resource/scan", args)

"""
Retrieves a list of analyzers.
"""
ListAnalyzers() = accessanalyzer("GET", "/analyzer")

"""
Retrieves information about the specified analyzer.

Required Parameters:
analyzerName
"""
GetAnalyzer(args) = accessanalyzer("GET", "/analyzer/{analyzerName}", args)

"""
Adds a tag to the specified resource.

Required Parameters:
resourceArn, tags
"""
TagResource(args) = accessanalyzer("POST", "/tags/{resourceArn}", args)

"""
Removes a tag from the specified resource.

Required Parameters:
resourceArn, tagKeys
"""
UntagResource(args) = accessanalyzer("DELETE", "/tags/{resourceArn}", args)

"""
Creates an archive rule for the specified analyzer. Archive rules automatically archive findings that meet the criteria you define when you create the rule.

Required Parameters:
analyzerName, filter, ruleName
"""
CreateArchiveRule(args) = accessanalyzer("PUT", "/analyzer/{analyzerName}/archive-rule", args)

"""
Retrieves information about an archive rule.

Required Parameters:
analyzerName, ruleName
"""
GetArchiveRule(args) = accessanalyzer("GET", "/analyzer/{analyzerName}/archive-rule/{ruleName}", args)

"""
Deletes the specified archive rule.

Required Parameters:
analyzerName, ruleName
"""
DeleteArchiveRule(args) = accessanalyzer("DELETE", "/analyzer/{analyzerName}/archive-rule/{ruleName}", args)

"""
Deletes the specified analyzer. When you delete an analyzer, Access Analyzer is disabled for the account in the current or specific Region. All findings that were generated by the analyzer are deleted. You cannot undo this action.

Required Parameters:
analyzerName
"""
DeleteAnalyzer(args) = accessanalyzer("DELETE", "/analyzer/{analyzerName}", args)

"""
Retrieves a list of resources of the specified type that have been analyzed by the specified analyzer..

Required Parameters:
analyzerArn
"""
ListAnalyzedResources(args) = accessanalyzer("POST", "/analyzed-resource", args)

"""
Updates the criteria and values for the specified archive rule.

Required Parameters:
analyzerName, filter, ruleName
"""
UpdateArchiveRule(args) = accessanalyzer("PUT", "/analyzer/{analyzerName}/archive-rule/{ruleName}", args)

"""
Updates the status for the specified findings.

Required Parameters:
analyzerArn, status
"""
UpdateFindings(args) = accessanalyzer("PUT", "/finding", args)
