include("../AWSCorePrototypeServices.jl")
using .Services: identitystore

"""
    ListGroups()

Lists the attribute name and value of the group that you specified in the search. We only support DisplayName as a valid filter attribute path currently, and filter is required. This API returns minimum attributes, including GroupId and group DisplayName in the response.

Required Parameters
{
  "IdentityStoreId": "The globally unique identifier for the identity store, such as d-1234567890. In this example, d- is a fixed prefix, and 1234567890 is a randomly generated string which contains number and lower case letters. This value is generated at the time that a new identity store is created."
}

Optional Parameters
{
  "MaxResults": "The maximum number of results to be returned per request, which is used in the ListUsers and ListGroups request to specify how many results to return in one page. The length limit is 50 characters.",
  "NextToken": "The pagination token used for the ListUsers and ListGroups APIs. This value is generated by the identity store service and is returned in the API response if the total results are more than the size of one page, and when this token is used in the API request to search for the next page.",
  "Filters": "A list of Filter objects, which is used in the ListUsers and ListGroups request. "
}
"""
ListGroups(args) = identitystore("ListGroups", args)

"""
    ListUsers()

Lists the attribute name and value of the user that you specified in the search. We only support UserName as a valid filter attribute path currently, and filter is required. This API returns minimum attributes, including UserId and UserName in the response.

Required Parameters
{
  "IdentityStoreId": "The globally unique identifier for the identity store, such as d-1234567890. In this example, d- is a fixed prefix, and 1234567890 is a randomly generated string which contains number and lower case letters. This value is generated at the time that a new identity store is created."
}

Optional Parameters
{
  "MaxResults": "The maximum number of results to be returned per request, which is used in the ListUsers and ListGroups request to specify how many results to return in one page. The length limit is 50 characters.",
  "NextToken": "The pagination token used for the ListUsers and ListGroups APIs. This value is generated by the identity store service and is returned in the API response if the total results are more than the size of one page, and when this token is used in the API request to search for the next page.",
  "Filters": "A list of Filter objects, which is used in the ListUsers and ListGroups request. "
}
"""
ListUsers(args) = identitystore("ListUsers", args)

"""
    DescribeUser()

Retrieves the user metadata and attributes from UserId in an identity store.

Required Parameters
{
  "UserId": "The identifier for a user in the identity store.",
  "IdentityStoreId": "The globally unique identifier for the identity store, such as d-1234567890. In this example, d- is a fixed prefix, and 1234567890 is a randomly generated string which contains number and lower case letters. This value is generated at the time that a new identity store is created."
}
"""
DescribeUser(args) = identitystore("DescribeUser", args)

"""
    DescribeGroup()

Retrieves the group metadata and attributes from GroupId in an identity store.

Required Parameters
{
  "IdentityStoreId": "The globally unique identifier for the identity store, such as d-1234567890. In this example, d- is a fixed prefix, and 1234567890 is a randomly generated string which contains number and lower case letters. This value is generated at the time that a new identity store is created.",
  "GroupId": "The identifier for a group in the identity store."
}
"""
DescribeGroup(args) = identitystore("DescribeGroup", args)
