include("../AWSCorePrototypeServices.jl")
using .Services: lambda

"""
Removes an event source mapping. This means AWS Lambda will no longer invoke the function for events in the associated source. This operation requires permission for the lambda:RemoveEventSource action.

Required Parameters:
UUID
"""
RemoveEventSource(args) = lambda("DELETE", "/2014-11-13/event-source-mappings/{UUID}", args)

"""
Returns the configuration information of the Lambda function and a presigned URL link to the .zip file you uploaded with UploadFunction so you can download the .zip file. Note that the URL is valid for up to 10 minutes. The configuration information is the same information you provided as parameters when uploading the function. This operation requires permission for the lambda:GetFunction action.

Required Parameters:
FunctionName
"""
GetFunction(args) = lambda("GET", "/2014-11-13/functions/{FunctionName}", args)

"""
Returns the configuration information of the Lambda function. This the same information you provided as parameters when uploading the function by using UploadFunction. This operation requires permission for the lambda:GetFunctionConfiguration operation.

Required Parameters:
FunctionName
"""
GetFunctionConfiguration(args) = lambda("GET", "/2014-11-13/functions/{FunctionName}/configuration", args)

"""
Creates a new Lambda function or updates an existing function. The function metadata is created from the request parameters, and the code for the function is provided by a .zip file in the request body. If the function name already exists, the existing Lambda function is updated with the new code and metadata.  This operation requires permission for the lambda:UploadFunction action.

Required Parameters:
FunctionName, FunctionZip, Runtime, Role, Handler, Mode
"""
UploadFunction(args) = lambda("PUT", "/2014-11-13/functions/{FunctionName}", args)

"""
Submits an invocation request to AWS Lambda. Upon receiving the request, Lambda executes the specified function asynchronously. To see the logs generated by the Lambda function execution, see the CloudWatch logs console. This operation requires permission for the lambda:InvokeAsync action.

Required Parameters:
FunctionName, InvokeArgs
"""
InvokeAsync(args) = lambda("POST", "/2014-11-13/functions/{FunctionName}/invoke-async/", args)

"""
Identifies a stream as an event source for an AWS Lambda function. It can be either an Amazon Kinesis stream or a Amazon DynamoDB stream. AWS Lambda invokes the specified function when records are posted to the stream. This is the pull model, where AWS Lambda invokes the function. For more information, go to AWS Lambda: How it Works in the AWS Lambda Developer Guide. This association between an Amazon Kinesis stream and an AWS Lambda function is called the event source mapping. You provide the configuration information (for example, which stream to read from and which AWS Lambda function to invoke) for the event source mapping in the request body.  Each event source, such as a Kinesis stream, can only be associated with one AWS Lambda function. If you call AddEventSource for an event source that is already mapped to another AWS Lambda function, the existing mapping is updated to call the new function instead of the old one.  This operation requires permission for the iam:PassRole action for the IAM role. It also requires permission for the lambda:AddEventSource action.

Required Parameters:
EventSource, FunctionName, Role
"""
AddEventSource(args) = lambda("POST", "/2014-11-13/event-source-mappings/", args)

"""
Updates the configuration parameters for the specified Lambda function by using the values provided in the request. You provide only the parameters you want to change. This operation must only be used on an existing Lambda function and cannot be used to update the function's code.  This operation requires permission for the lambda:UpdateFunctionConfiguration action.

Required Parameters:
FunctionName
"""
UpdateFunctionConfiguration(args) = lambda("PUT", "/2014-11-13/functions/{FunctionName}/configuration", args)

"""
Returns a list of event source mappings you created using the AddEventSource (see AddEventSource), where you identify a stream as event source. This list does not include Amazon S3 event sources.  For each mapping, the API returns configuration information. You can optionally specify filters to retrieve specific event source mappings. This operation requires permission for the lambda:ListEventSources action.
"""
ListEventSources() = lambda("GET", "/2014-11-13/event-source-mappings/")

"""
Returns a list of your Lambda functions. For each function, the response includes the function configuration information. You must use GetFunction to retrieve the code for your function. This operation requires permission for the lambda:ListFunctions action.
"""
ListFunctions() = lambda("GET", "/2014-11-13/functions/")

"""
Deletes the specified Lambda function code and configuration. This operation requires permission for the lambda:DeleteFunction action.

Required Parameters:
FunctionName
"""
DeleteFunction(args) = lambda("DELETE", "/2014-11-13/functions/{FunctionName}", args)

"""
Returns configuration information for the specified event source mapping (see AddEventSource). This operation requires permission for the lambda:GetEventSource action.

Required Parameters:
UUID
"""
GetEventSource(args) = lambda("GET", "/2014-11-13/event-source-mappings/{UUID}", args)
