include("../AWSCorePrototypeServices.jl")
using .Services: personalize_events

"""
    PutEvents()

Records user interaction event data. For more information see event-record-api.

Required Parameters
{
  "eventList": "A list of event data from the session.",
  "sessionId": "The session ID associated with the user's visit. Your application generates the sessionId when a user first visits your website or uses your application. Amazon Personalize uses the sessionId to associate events with the user before they log in. For more information see event-record-api.",
  "trackingId": "The tracking ID for the event. The ID is generated by a call to the CreateEventTracker API."
}

Optional Parameters
{
  "userId": "The user associated with the event."
}
"""
PutEvents(args) = personalize_events("POST", "/events", args)
