name: AWSMetadata

# Change this to daily cron in prod
# on: [push]

jobs:
  AWSCorePrototype:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: UpdateAPI
        run: julia -e 'import Pkg; Pkg.develop(Pkg.PackageSpec(url="https://github.com/mattBrzezinski/JuliaCloud-AWS-State.git")); using AWSCorePrototype; AWSCorePrototype.AWSMetadata.parse_aws_metadata()'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
         path: "~/.julia/dev/AWSCorePrototype/"
         token: ${{ secrets.GITHUB_TOKEN }}