name: AWS
on: ["push"]

jobs:
  AWS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1] 
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: mattBrzezinski/JuliaCloud-AWS-State
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - name: UpdateAPI
        run: sudo julia --project -e 'using AWSCorePrototype; AWSCorePrototype.AWSMetadata.parse_aws_metadata();'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
         token: ${{ secrets.GITHUB_TOKEN }}