name: AWSMetadata

on: [push]

jobs:
  AWSCorePrototype:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: LoadPath
        run: julia -e 'print(LOAD_PATH)'
      - name: ParseMetadata
        run: sudo julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/mattBrzezinski/JuliaCloud-AWS-State.git")); using AWSCorePrototype; AWSCorePrototype.AWSMetadata.parse_aws_metadata()'
